### ISSUE TITLE
Example App on Linux: Popup login window does not seem to relate to ID in the Welcome window 

### ISSUE THREAD

**Issue by gjwgit** [anusii/solid_auth#2]
Running `flutter run -d linux`

Web ID is for charlieb

![image](https://user-images.githubusercontent.com/1681429/151682364-fe4b3d9e-2460-4d5d-af23-99474f7a0cae.png)

In login window popup login as kayon

![image](https://user-images.githubusercontent.com/1681429/151682402-1bed4800-8df0-48ae-9b60-183d42cc0703.png)

and so see Kayon details:

![image](https://user-images.githubusercontent.com/1681429/151682349-2f164cb9-f351-438b-9c83-952c96a6febe.png)

Perhaps the Username in the login screen should default to "charlieb" from the Web ID supplied? The user can then override it but then that is clear.

**Comment by anushkavidanage** [comment]
The text area in the main screen can include either WebIDs or links to SOLID POD providers. A WebID is specifically used for accessing public information. If you try to login to a POD you don't need to provide the complete WebID as input, just the link to POD provider will be enough.

**Comment by gjwgit** [comment]
As a demo I think this is fine. Closing.
